export const GET_BOOK_ACTION = "GET_BOOK_ACTION";
export const GET_CATEGORIES_ACTION = "GET_CATEGORIES_ACTION";
export const GET_SEARCH_ACTION = "GET_SEARCH_ACTION";

export const GET_LOGIN_ACTION = "GET_LOGIN_ACTION";
export const GET_REGISTER_ACTION = "GET_REGISTER_ACTION";
export const GET_LOGOUT_ACTION = "GET_LOGOUT_ACTION";
